services:
  mongo:
    container_name: mongo_db
    image: mongo
    restart: always
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD} 
      MONGO_INITDB_DATABASE: ${MONGO_INIT_DB}
    volumes:
      - mongo_data:/data/db
    networks:
      - my_network 
  
  mongo-express: 
    container_name: mongo_admin
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root 
      ME_CONFIG_MONGODB_ADMINPASSWORD: example 
      ME_CONFIG_MONGODB_SERVER: mongo 
    networks:
      - my_network

  postgres: 
    container_name: postgres
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes: 
      - /data/postgres:/data/postgres
    env_file:
      - docker.env 
    networks: 
      - postgres 

  pgadmin:
    links:
      - postgres:postgres 
    container_name: pgadmin 
    image: dpage/pgadmin4 
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
    - docker.env
    networks:
    - postgres

volumes:
  mongo_data:

networks:
  my_network:
    driver: bridge
  postgres:
    driver: bridge

  

